version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    ports:
      - "5672:5672" # RabbitMQ bağlantı portu
      - "15672:15672" # RabbitMQ web arayüzü
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
